HIVE-2883 [jira] Metastore client doesnt close connection properly
Summary:
https://issues.apache.org/jira/browse/HIVE-2883

Here is the patch which gets rid of this problem as per my hypothesis. I also
tested it and the above noted stack trace doesnt occur anymore.

While closing connection, it always fail with following trace. Seemingly, it
doesnt have any harmful effects.

12/03/20 10:55:02 ERROR hive.metastore: Unable to shutdown local metastore
client
org.apache.thrift.transport.TTransportException: Cannot write to null
outputStream
	at
org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:142)
	at
org.apache.thrift.protocol.TBinaryProtocol.writeI32(TBinaryProtocol.java:163)
	at
org.apache.thrift.protocol.TBinaryProtocol.writeMessageBegin(TBinaryProtocol.java:91)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
	at
com.facebook.fb303.FacebookService$Client.send_shutdown(FacebookService.java:421)
	at com.facebook.fb303.FacebookService$Client.shutdown(FacebookService.java:415)
	at
org.apache.hadoop.hive.metastore.HiveMetaStoreClient.close(HiveMetaStoreClient.java:310)

Test Plan: EMPTY

Reviewers: JIRA, cwsteinbach

Reviewed By: cwsteinbach

Differential Revision: https://reviews.facebook.net/D2613

git-svn-id: https://svn.apache.org/repos/asf/hive/trunk@1329461 13f79535-47bb-0310-9956-ffa450edef68